//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanyApp.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactPerson
    {
        public int contactPersonID { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string position { get; set; }
        public Nullable<int> companyID { get; set; }
        public Nullable<int> userID { get; set; }
        public bool isDeleted { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual User User { get; set; }
    }
}
